# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-28 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drm.Fun', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='组名')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='说明')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('fun', models.ManyToManyField(to='drm.Fun')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='预案编号')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='预案名称')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='预案描述')),
                ('sign', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否签到')),
                ('rto', models.IntegerField(blank=True, null=True, verbose_name='RTO')),
                ('rpo', models.IntegerField(blank=True, null=True, verbose_name='RPO')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='页面链接')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='预案类型')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('creatuser', models.CharField(blank=True, max_length=50, verbose_name='发起人')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('run_reason', models.CharField(blank=True, max_length=2500, null=True, verbose_name='启动原因')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.Process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('senduser', models.CharField(blank=True, max_length=50, null=True, verbose_name='发送人')),
                ('receiveuser', models.CharField(blank=True, max_length=50, null=True, verbose_name='接收人')),
                ('receiveauth', models.CharField(blank=True, max_length=50, null=True, verbose_name='接收角色')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='任务类型')),
                ('content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='任务内容')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('result', models.CharField(blank=True, max_length=5000, null=True, verbose_name='处理结果')),
                ('explain', models.CharField(blank=True, max_length=5000, null=True, verbose_name='处理说明')),
                ('processrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.ProcessRun')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='脚本编号')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='脚本名称')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机IP')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='端口号')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='连接类型')),
                ('runtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='运行类型')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='脚本文件名')),
                ('paramtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='参数类型')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本参数')),
                ('scriptpath', models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本文件路径')),
                ('runpath', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行路径')),
                ('command', models.CharField(blank=True, max_length=500, null=True, verbose_name='生产命令行')),
                ('maxtime', models.IntegerField(blank=True, null=True, verbose_name='超时时间')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='预计耗时')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('succeedtext', models.CharField(blank=True, max_length=500, null=True, verbose_name='成功代码')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('result', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行结果')),
                ('explain', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行说明')),
                ('runlog', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行日志')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='步骤编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='步骤名称')),
                ('approval', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否审批')),
                ('skip', models.CharField(blank=True, max_length=10, null=True, verbose_name='能否跳过')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='预计耗时')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('last', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='drm.Step', verbose_name='上一步')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drm.Step', verbose_name='父节点')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.Process')),
            ],
        ),
        migrations.CreateModel(
            name='StepRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('parameter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行参数')),
                ('result', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行结果')),
                ('explain', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运行说明')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('processrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.ProcessRun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Step')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='说明')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司')),
                ('tell', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('forgetpassword', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改密码地址')),
                ('group', models.ManyToManyField(to='drm.Group')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drm.UserInfo', verbose_name='父节点')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='确认项')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='状态')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.Step')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyItemsRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='确认项')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='状态')),
                ('has_verified', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否确认')),
                ('verify_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.VerifyItems')),
            ],
        ),
        migrations.AddField(
            model_name='scriptrun',
            name='steprun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.StepRun'),
        ),
        migrations.AddField(
            model_name='script',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Step'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='steprun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.StepRun'),
        ),
    ]
