# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0002_auto_20180828_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='颜色'),
        ),
    ]
