# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0005_auto_20180905_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='记录'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='logtype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='日志类型'),
        ),
        migrations.AddField(
            model_name='scriptrun',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='记录'),
        ),
        migrations.AddField(
            model_name='steprun',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='记录'),
        ),
    ]
