# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='current_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邀请时间'),
        ),
    ]
