# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0008_invitation_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='rto_count_in',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否算入RTO'),
        ),
    ]
