# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0010_auto_20181030_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='log_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='日志地址'),
        ),
        migrations.AddField(
            model_name='step',
            name='remark',
            field=models.CharField(blank=True, help_text='告知业务人员灾备环境地址等信息', max_length=500, null=True, verbose_name='备注'),
        ),
    ]
