# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0011_auto_20181108_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=64, null=True, verbose_name='上传人')),
                ('upload', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('file_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
            ],
        ),
    ]
