# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-06 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0012_knowledgefiledownload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgefiledownload',
            old_name='upload',
            new_name='upload_time',
        ),
    ]
