# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-06 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0013_auto_20181206_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefiledownload',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='状态'),
        ),
    ]
