# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-06 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0017_auto_20190806_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='ip',
        ),
    ]
