# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0018_remove_script_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_text',
            field=models.TextField(blank=True, default='', verbose_name='脚本内容'),
        ),
    ]
