# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0019_script_script_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='终端client_id')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='终端client_name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='客户端相关信息')),
            ],
        ),
    ]
