# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-03 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0021_target_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='源端client_id')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='源端client_name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='客户端相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Target', verbose_name='默认关联终端')),
            ],
        ),
    ]
