# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0024_auto_20190903_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='recover_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指定恢复时间点'),
        ),
        migrations.AddField(
            model_name='processrun',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Target', verbose_name='oracle恢复流程指定目标客户端'),
        ),
    ]
