# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-09 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0029_clientmanage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmanage',
            old_name='status',
            new_name='state',
        ),
    ]
