# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0031_auto_20190911_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='browse_job_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='指点时间点的备份任务id'),
        ),
    ]
