# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0035_processrun_scn'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='data_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='数据重定向路径'),
        ),
    ]
