# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-20 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0036_processrun_data_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='SCN',
        ),
    ]
