# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0038_delete_clientmanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='origin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='源客户端'),
        ),
    ]
