# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-29 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0042_processschedule_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='processschedule',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='流程计划名称'),
        ),
    ]
