# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0043_processschedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
        migrations.AddField(
            model_name='processschedule',
            name='schedule_type',
            field=models.IntegerField(choices=[(1, '每日'), (2, '每周'), (3, '每月')], default=1, null=True),
        ),
    ]
