# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0045_step_force_exec'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='copy_priority',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='拷贝优先级：1：主拷贝；2：辅助拷贝'),
        ),
        migrations.AddField(
            model_name='origin',
            name='data_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='数据文件重定向路径'),
        ),
    ]
