# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0046_auto_20191028_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='copy_priority',
            field=models.IntegerField(blank=True, choices=[(1, '主拷贝'), (2, '辅助拷贝')], default=1, null=True, verbose_name='拷贝优先级：1：主拷贝；2：辅助拷贝'),
        ),
    ]
