# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0050_remove_target_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrun',
            name='copy_priority',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='优先拷贝顺序'),
        ),
        migrations.AlterField(
            model_name='script',
            name='commv_interface',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='commvault接口脚本'),
        ),
    ]
