# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0051_auto_20191029_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='curSCN',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前备份nextSCN-1'),
        ),
    ]
