# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-31 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0054_auto_20191030_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrun',
            name='curSCN',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='当前备份nextSCN-1'),
        ),
    ]
