# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0055_auto_20191031_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='rto',
            field=models.IntegerField(default=0, null=True, verbose_name='流程RTO'),
        ),
    ]
