# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0059_utilsmanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSpaceWeeklyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(default=0, null=True, verbose_name='MediaID')),
                ('capacity_avaible', models.BigIntegerField(default=0, null=True, verbose_name='可用容量')),
                ('space_reserved', models.BigIntegerField(default=0, null=True, verbose_name='保留空间')),
                ('total_space', models.BigIntegerField(default=0, null=True, verbose_name='总容量')),
                ('extract_time', models.DateTimeField(null=True, verbose_name='取数时间')),
                ('point_tag', models.CharField(default='', max_length=128, null=True, verbose_name='用以判断同一记录')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='工具')),
            ],
        ),
    ]
