# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0060_diskspaceweeklydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='接口实例名称')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='接口实例说明')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='执行顺序')),
                ('params', models.TextField(default='', null=True, verbose_name='脚本内容参数')),
                ('log_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='日志地址')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('hosts_manage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.HostsManage', verbose_name='选择主机')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Origin', verbose_name='源端客户端')),
            ],
        ),
        migrations.RemoveField(
            model_name='script',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='script',
            name='hosts_manage',
        ),
        migrations.RemoveField(
            model_name='script',
            name='log_address',
        ),
        migrations.RemoveField(
            model_name='script',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='script',
            name='scriptpath',
        ),
        migrations.RemoveField(
            model_name='script',
            name='step',
        ),
        migrations.AddField(
            model_name='script',
            name='config',
            field=models.TextField(default='<root></root>', null=True, verbose_name='接口参数'),
        ),
        migrations.AddField(
            model_name='script',
            name='pnode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drm.Script', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='script',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='节点/接口说明'),
        ),
        migrations.AddField(
            model_name='script',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='script',
            name='commv_interface',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='commvault接口类名'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interface_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='接口类型'),
        ),
        migrations.AddField(
            model_name='scriptinstance',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Script', verbose_name='源接口'),
        ),
        migrations.AddField(
            model_name='scriptinstance',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.Step', verbose_name='步骤'),
        ),
        migrations.AddField(
            model_name='scriptinstance',
            name='utils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='工具'),
        ),
    ]
