# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0061_auto_20200713_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='config',
            field=models.TextField(default='<root></root>', null=True, verbose_name='流程参数'),
        ),
    ]
