# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0062_process_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='utils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具'),
        ),
    ]
