# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0065_auto_20200713_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='节点/客户端说明'),
        ),
    ]
