# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0066_hostsmanage_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='源端client_id')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='源端client_name')),
                ('type', models.TextField(blank=True, null=True, verbose_name='客户端类型')),
                ('agentType', models.TextField(blank=True, null=True, verbose_name='应用类型')),
                ('instanceName', models.TextField(blank=True, null=True, verbose_name='实例名')),
                ('info', models.TextField(blank=True, null=True, verbose_name='客户端相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('hostsmanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.HostsManage', verbose_name='客户端')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
    ]
