# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0067_cvclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvclient',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceclient', to='drm.CvClient', verbose_name='默认关联终端'),
        ),
    ]
