# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0069_auto_20200719_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='host',
            field=models.ManyToManyField(to='drm.HostsManage'),
        ),
    ]
