# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0070_group_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbCopyClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True, verbose_name='客户端类型')),
                ('dbType', models.TextField(blank=True, null=True, verbose_name='数据库类型')),
                ('info', models.TextField(blank=True, null=True, verbose_name='客户端相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('hostsmanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.HostsManage', verbose_name='客户端')),
                ('std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri', to='drm.DbCopyClient', verbose_name='备库')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
    ]
