# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-29 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0071_dbcopyclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbcopyclient',
            name='utils',
        ),
    ]
