# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0072_remove_dbcopyclient_utils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbcopyclient',
            old_name='dbType',
            new_name='dbtype',
        ),
        migrations.RemoveField(
            model_name='dbcopyclient',
            name='type',
        ),
        migrations.AddField(
            model_name='dbcopyclient',
            name='hosttype',
            field=models.TextField(blank=True, null=True, verbose_name='主机类型'),
        ),
        migrations.AlterField(
            model_name='dbcopyclient',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='数据库相关信息'),
        ),
    ]
