# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-31 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0073_auto_20200729_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='browse_job_id',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='copy_priority',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='curSCN',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='data_path',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='db_open',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='target',
        ),
    ]
