# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-31 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0074_auto_20200731_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='info',
            field=models.TextField(default='', null=True, verbose_name='恢复所需参数,如：target,origin,browse_job_id,data_path,copy_priority,curSCN,db_open'),
        ),
    ]
