# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0075_processrun_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='backprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_backprocess_set', to='drm.Process', verbose_name='回切流程'),
        ),
        migrations.AddField(
            model_name='process',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_primary_set', to='drm.HostsManage', verbose_name='主数据库'),
        ),
    ]
