# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0076_auto_20200731_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrun',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.ScriptInstance'),
        ),
    ]
