# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0077_auto_20200801_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbcopyclient',
            name='std',
        ),
        migrations.AddField(
            model_name='dbcopyclient',
            name='pri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std', to='drm.DbCopyClient', verbose_name='备库'),
        ),
    ]
