# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0078_auto_20200812_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drm.Process', verbose_name='父节点'),
        ),
    ]
