# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0079_process_pnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvmMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='kvm虚拟机名称')),
                ('filesystem', models.TextField(blank=True, null=True, verbose_name='kvm虚拟机文件系统')),
                ('info', models.TextField(blank=True, null=True, verbose_name='kvm虚拟机相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('hostsmanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.HostsManage', verbose_name='客户端')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
    ]
