# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0083_process_cv_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZfsSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='zfs快照名称')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('kvmmachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.KvmMachine', verbose_name='kvm虚拟机')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
    ]
