# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0087_process_cv_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='process',
            field=models.ManyToManyField(to='drm.Process'),
        ),
    ]
