# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0090_process_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvmCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='副本名称')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='副本IP')),
                ('hostname', models.CharField(blank=True, max_length=30, null=True, verbose_name='副本主机名')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('create_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('kvmmachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.KvmMachine', verbose_name='kvm虚拟机')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
        migrations.RemoveField(
            model_name='zfssnapshot',
            name='kvmmachine',
        ),
        migrations.RemoveField(
            model_name='zfssnapshot',
            name='utils',
        ),
        migrations.DeleteModel(
            name='ZfsSnapshot',
        ),
    ]
