# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-25 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0091_auto_20200825_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmcopy',
            name='create_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
