# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0093_auto_20200827_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='nodetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='节点类型'),
        ),
    ]
