# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-01 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0094_process_nodetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='nodetype',
        ),
    ]
