# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-01 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0096_auto_20200901_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='procosstype',
            new_name='processtype',
        ),
    ]
