# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0098_kvmcopy_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('os', models.CharField(blank=True, max_length=30, null=True, verbose_name='操作系统')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='模板类型')),
                ('path', models.CharField(blank=True, max_length=50, null=True, verbose_name='模板路径')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drm.UtilsManage', verbose_name='关联工具')),
            ],
        ),
        migrations.AddField(
            model_name='kvmcopy',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='副本密码'),
        ),
    ]
