# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0099_auto_20200930_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='disktemplate',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='状态'),
        ),
    ]
