# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0100_disktemplate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='disktemplate',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='文件名称'),
        ),
    ]
