# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-11-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0101_disktemplate_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fun',
            name='if_new_wd',
            field=models.CharField(blank='0', max_length=20, null=True, verbose_name='是否新窗口打开'),
        ),
    ]
