# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0103_auto_20201223_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsdrmjob',
            name='step',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='流程中的步骤号'),
        ),
    ]
