# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0104_tsdrmjob_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='component',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='control',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='workflow',
        ),
        migrations.AddField(
            model_name='tsdrmjob',
            name='modelguid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='模型guid'),
        ),
    ]
