# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0105_auto_20201224_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsdrmjob',
            name='modelguid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='模型guid'),
        ),
    ]
