# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-12-24 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0106_auto_20201224_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subschedule',
            name='s',
        ),
        migrations.RemoveField(
            model_name='tsdrmcomponent',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmcomponent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tsdrmcomponent',
            name='pnode',
        ),
        migrations.RemoveField(
            model_name='tsdrmcomponent',
            name='updateuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmcontrol',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmcontrol',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tsdrmcontrol',
            name='pnode',
        ),
        migrations.RemoveField(
            model_name='tsdrmcontrol',
            name='updateuser',
        ),
        migrations.RemoveField(
            model_name='tsdrminstance',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='tsdrminstance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tsdrminstance',
            name='pnode',
        ),
        migrations.RemoveField(
            model_name='tsdrminstance',
            name='updateuser',
        ),
        migrations.RemoveField(
            model_name='tsdrminstance',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='pjob',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='startuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmjob',
            name='updateuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmschedule',
            name='dj_periodictask',
        ),
        migrations.RemoveField(
            model_name='tsdrmschedule',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='tsdrmworkflow',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='tsdrmworkflow',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tsdrmworkflow',
            name='pnode',
        ),
        migrations.RemoveField(
            model_name='tsdrmworkflow',
            name='updateuser',
        ),
        migrations.DeleteModel(
            name='SubSchedule',
        ),
        migrations.DeleteModel(
            name='TSDRMComponent',
        ),
        migrations.DeleteModel(
            name='TSDRMControl',
        ),
        migrations.DeleteModel(
            name='TSDRMInstance',
        ),
        migrations.DeleteModel(
            name='TSDRMJob',
        ),
        migrations.DeleteModel(
            name='TSDRMSchedule',
        ),
        migrations.DeleteModel(
            name='TSDRMWorkflow',
        ),
    ]
