# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2021-04-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0109_auto_20201229_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='DictList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='条目名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='状态')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('dictindex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.DictIndex')),
            ],
        ),
        migrations.AlterField(
            model_name='tsdrmworkflow',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
