# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2021-04-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0111_auto_20210413_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='monitor',
            field=models.TextField(default='<root></root>', null=True, verbose_name='性能监控'),
        ),
    ]
