# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2021-04-27 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0113_syslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syslog',
            old_name='userid',
            new_name='user',
        ),
    ]
